# Generated by Django 5.2 on 2025-05-27 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('asin', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('title', models.TextField()),
                ('author', models.CharField(max_length=255)),
                ('sold_by', models.CharField(blank=True, max_length=255, null=True)),
                ('img_url', models.URLField()),
                ('product_url', models.URLField(blank=True, null=True)),
                ('stars', models.DecimalField(decimal_places=1, max_digits=3)),
                ('reviews', models.IntegerField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('is_kindle_unlimited', models.BooleanField()),
                ('category_id', models.IntegerField(blank=True, null=True)),
                ('is_best_seller', models.BooleanField()),
                ('is_editors_pick', models.BooleanField()),
                ('is_goodreads_choice', models.BooleanField()),
                ('published_date', models.DateField(blank=True, null=True)),
                ('category_name', models.CharField(max_length=255)),
            ],
        ),
    ]
