# Generated by Django 5.2 on 2025-05-27 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='category_id',
            new_name='categoryId',
        ),
        migrations.RenameField(
            model_name='book',
            old_name='category_name',
            new_name='categoryName',
        ),
        migrations.RenameField(
            model_name='book',
            old_name='img_url',
            new_name='imgUrl',
        ),
        migrations.RenameField(
            model_name='book',
            old_name='is_best_seller',
            new_name='isBestSeller',
        ),
        migrations.RenameField(
            model_name='book',
            old_name='is_editors_pick',
            new_name='isEditorsPick',
        ),
        migrations.RenameField(
            model_name='book',
            old_name='is_goodreads_choice',
            new_name='isGoodreadsChoice',
        ),
        migrations.RenameField(
            model_name='book',
            old_name='product_url',
            new_name='productUrl',
        ),
        migrations.RenameField(
            model_name='book',
            old_name='published_date',
            new_name='publishedDate',
        ),
        migrations.RenameField(
            model_name='book',
            old_name='sold_by',
            new_name='soldBy',
        ),
        migrations.RemoveField(
            model_name='book',
            name='is_kindle_unlimited',
        ),
        migrations.AddField(
            model_name='book',
            name='isKindleUnlimited',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='stars',
            field=models.DecimalField(decimal_places=2, max_digits=3),
        ),
    ]
