# Generated by Django 5.2 on 2025-05-27 17:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_rename_category_id_book_categoryid_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='isGoodreadsChoice',
            new_name='isGoodReadsChoice',
        ),
    ]
