# Generated by Django 5.2 on 2025-05-27 21:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_rename_isgoodreadschoice_book_isgoodreadschoice'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='categoryId',
            new_name='category_id',
        ),
        migrations.RenameField(
            model_name='book',
            old_name='categoryName',
            new_name='category_name',
        ),
        migrations.RenameField(
            model_name='book',
            old_name='productUrl',
            new_name='productURL',
        ),
    ]
