# Generated by Django 5.2 on 2025-05-27 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_rename_categoryid_book_category_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='isBestSeller',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='isEditorsPick',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='isGoodReadsChoice',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
